template:
  path: dependencies/dependent_template_local_export.json


parameters:
  DependentStackName: !stack_output_external "{{project_code}}-external-stack-output-outputter::StackName ::eu-west-1"
